name: docker-build-and-push
on:
  push:
    branches:
      - main
jobs:
 build-and-push-docker:
          runs-on: ubuntu-latest
          steps:
            - name: Check out the repository
              uses: actions/checkout@v2  
            - name: Extract version from package.json
              id: package_version
              run: echo ::set-output name=VERSION::$(jq -r .version package.json)
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1   
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}      
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: mohamedbedier/beesens:${{ steps.package_version.outputs.VERSION }}
