name: docker-build-and-push
on:
  push:
    branches:
      - main
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Extract version from package.json
        id: package_version
        run: echo ::set-output name=VERSION::$(jq -r .version package.json)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker image
        run: docker build -t mohamedbedier/beesens:${{ steps.package_version.outputs.VERSION }} .

      - name: Push Docker image
        run: docker push mohamedbedier/beesens:${{ steps.package_version.outputs.VERSION }}

      - name: Clone bee-sensors-manifest repository
        uses: actions/checkout@v3
        with:
          repository: bedier1/bee-sensors-manifest-
          token: ${{ secrets.GITHUB_TOKEN }} # Using GitHub Token for authentication
          path: bee-sensors-manifest-
      - name: Update Helm chart
        run: |
          ls -la
          pwd
          sed -i "s/tag: .*/tag: \"${{ steps.package_version.outputs.VERSION }}\"/" bee-sensors-manifest-/helm/beechart/values.yaml
          cd bee-sensors-manifest-
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/beechart/values.yaml
          git commit -m "Update image tag to ${{ steps.package_version.outputs.VERSION }}"
          git push