name: docker-build-and-push
on:
  push:
    branches:
      - main
jobs:
 build-and-push-docker:
          runs-on: ubuntu-latest
          steps:
            - name: Check out the repository
              uses: actions/checkout@v3 
            - name: Extract version from package.json
              id: package_version
              run: echo ::set-output name=VERSION::$(jq -r .version package.json)
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3  
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}      
            - name: Build Docker image
              run: docker build -t mohamedbedier/beesens:${{ steps.package_version.outputs.VERSION }} .
        
            - name: Push Docker image
              run: docker push mohamedbedier/beesens:${{ steps.package_version.outputs.VERSION }}

