name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v14.21.3
      - name: Install Node.js dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          #     eslint: true
          token: ${{ secrets.GHS}}
          prettier: true
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: run-linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: v14.21.3

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Start Application
      run: node server.js &
    - name: Check /version endpoint
      run: |
        sudo apt install jq -y
        sleep 5 # give your application some time to start
        VERSION=$(curl http://localhost:3000/api/version | jq -r  .version)
        echo "Version endpoint response: $VERSION"
        if [[ $VERSION != "1.0.0" ]]; then
          echo "Version mismatch"
          exit 1
        fi
