name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v14.21.3
      - name: Install Node.js dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          #     eslint: true
          token: ${{ secrets.GHS }}
          prettier: true
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-app:
    needs: run-linters
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v14.21.3
      - name: Install dependencies
        run: npm install
      - name: Start Application
        run: |
         sudo apt-get install -y redis-tools redis-server
          export box1=5eba5fbad46fb8001b799786
          export box2=5e60cf5557703e001bdae7f8
          export box3=5eb99cacd46fb8001b2ce04c
          export REDIS_HOST=localhost
          export REDIS_PORT=6379
          node server.js &

      - name: Check /version endpoint
        run: |
          sudo apt install jq -y
          sleep 5 # give your application some time to start
          VERSION=$(curl http://localhost:3000/api/version | jq -r  .version)
          echo "Version endpoint response: $VERSION"
          if [[ $VERSION != "1.1.1" ]]; then
            echo "Version mismatch"
            exit 1
          fi
      - name: Install Venom
        run: |
          curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom && chmod +x /usr/local/bin/venom
          export IS_TTY=true
          venom run testsuite.yml
