---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp

  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: myapp-monitoring
  endpoints:
    - port: http
      path: /metrics