---
apiVersion: v1
kind: Service
metadata:
  
  name: myapp-prom
  labels:
    app: myapp-monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: beechart
    app.kubernetes.io/name: beechart
    